"""Desktop presentation for the MuMu ranked assistant."""
import tkinter as tk
from tkinter import ttk
import webbrowser

BG='#202328'
PANEL='#292d33'
TEXT='#eef0f3'
MUTED='#a3aab5'
GOLD='#a8c7f3'


def build_panel(app):
    root=app.root
    root.geometry('1160x760')
    root.minsize(1080,720)
    root.configure(bg=BG)
    root.option_add('*TCombobox*Listbox.background',PANEL)
    root.option_add('*TCombobox*Listbox.foreground',TEXT)
    style=ttk.Style(root)
    style.theme_use('clam')
    style.configure('.',background=BG,foreground=TEXT,font=('Microsoft JhengHei UI',10))
    style.configure('TFrame',background=BG)
    style.configure('Card.TFrame',background=PANEL)
    style.configure('TLabel',background=BG,foreground=TEXT)
    style.configure('Muted.TLabel',foreground=MUTED)
    style.configure('Title.TLabel',font=('Microsoft JhengHei UI',20,'bold'))
    style.configure('Heading.TLabel',font=('Microsoft JhengHei UI',12,'bold'))
    style.configure('TButton',background='#252525',foreground=TEXT,borderwidth=1,padding=(12,6),bordercolor='#454545',lightcolor='#454545',darkcolor='#454545',relief='flat')
    style.map('TButton',background=[('active','#383838')])
    style.configure('Accent.TButton',background='#719fd8',foreground='#101b2a',font=('Microsoft JhengHei UI',11,'bold'))
    style.map('Accent.TButton',background=[('disabled','#3a4552'),('active','#91b8e8')])
    style.map('TButton',foreground=[('disabled','#717780')],background=[('disabled','#282b30'),('active','#3a414a')])
    style.configure('Stop.TButton',background='#583437',foreground='#ffdddd')
    style.configure('TEntry',fieldbackground=PANEL,foreground=TEXT,insertcolor=TEXT,padding=7)
    style.configure('TCombobox',fieldbackground=PANEL,background='#252525',foreground=TEXT,padding=6)
    style.map('TCombobox',fieldbackground=[('readonly',PANEL)],foreground=[('readonly',TEXT)])
    style.configure('TSpinbox',fieldbackground=PANEL,foreground=TEXT,padding=6)
    style.configure('TNotebook',background=BG,borderwidth=0)
    for name in ('TNotebook','TNotebook.Tab','TEntry','TCombobox','TSpinbox'):
        style.configure(name,bordercolor='#404040',lightcolor=BG,darkcolor=BG)
    style.configure('TNotebook.Tab',padding=(48,9),background=PANEL,foreground=MUTED)
    style.map('TNotebook.Tab',background=[('selected',BG)],foreground=[('selected',TEXT)],padding=[('selected',(48,9)),('!selected',(48,9))])
    style.configure('Treeview',background=PANEL,fieldbackground=PANEL,foreground=TEXT,rowheight=30,borderwidth=0)
    style.configure('Treeview.Heading',background='#252525',foreground=MUTED,padding=7)
    style.configure('Treeview',bordercolor='#404040',lightcolor=BG,darkcolor=BG,relief='flat')
    style.configure('Treeview.Heading',bordercolor='#404040',lightcolor=BG,darkcolor=BG,relief='flat')
    style.configure('TSeparator',background='#404040')
    style.configure('Vertical.TScrollbar',background='#46505c',troughcolor='#1b1e22',arrowcolor=MUTED,bordercolor=BG,lightcolor=BG,darkcolor=BG)
    style.map('Treeview',background=[('selected','#4b5967')])
    shell=ttk.Frame(root,padding=0);shell.pack(fill='both',expand=True)
    nav=tk.Frame(shell,bg='#191c20',width=166)
    nav.pack(side='left',fill='y')
    nav.pack_propagate(False)
    tk.Label(nav,text='LAYA',bg='#191c20',fg=TEXT,font=('Segoe UI',22,'bold')).pack(anchor='w',padx=22,pady=(28,0))
    tk.Label(nav,text='爐石助手',bg='#191c20',fg=MUTED,font=('Microsoft JhengHei UI',10)).pack(anchor='w',padx=24,pady=(0,32))
    nav_items=tk.Frame(nav,bg='#191c20');nav_items.pack(fill='x')
    tk.Label(nav,text='v0.1.0  ·  MuMu',bg='#191c20',fg=MUTED,font=('Segoe UI',9)).pack(side='bottom',anchor='w',padx=22,pady=22)
    style.layout('Pages.TNotebook.Tab',[])
    book=ttk.Notebook(shell,style='Pages.TNotebook');book.pack(fill='both',expand=True)
    ranked=ttk.Frame(book,padding=(28,28));library=ttk.Frame(book,padding=24);advanced=ttk.Frame(book,padding=24)
    book.add(ranked,text='排位作業');book.add(library,text='牌組與環境');book.add(advanced,text='進階設定')
    preview=ttk.Frame(book,padding=16)
    book.insert(2,preview,text='遊戲畫面')
    navigation=[]
    def select_page(page):
        book.select(page)
        for target,button,line in navigation:
            button.configure(fg=TEXT if target is page else MUTED,bg='#303944' if target is page else '#191c20')
            line.configure(bg='#89b4eb' if target is page else '#191c20')
    for column,(page,title) in enumerate([(ranked,'排位作業'),(library,'牌組與環境'),(preview,'遊戲畫面'),(advanced,'進階設定')]):
        cell=tk.Frame(nav_items,bg='#191c20')
        cell.pack(fill='x',pady=3)
        button=tk.Button(cell,text=title,command=lambda page=page:select_page(page),
                         bg='#191c20',fg=MUTED,activebackground='#303944',activeforeground=TEXT,
                         relief='flat',borderwidth=0,highlightthickness=0,pady=11,
                         font=('Microsoft JhengHei UI',10))
        line=tk.Frame(cell,width=3,bg='#191c20');line.pack(side='left',fill='y')
        button.pack(side='left',fill='x',expand=True)
        navigation.append((page,button,line))
    select_page(ranked)
    heading=ttk.Frame(ranked);heading.pack(fill='x',pady=(0,24))
    ttk.Label(heading,text='排位作業',style='Title.TLabel').pack(anchor='w')
    ttk.Label(heading,text='選好牌組，交給 Laya。',style='Muted.TLabel').pack(anchor='w',pady=(6,0))
    body=ttk.Frame(ranked);body.pack(fill='both',expand=True)
    sidebar=ttk.Frame(body,width=302,padding=20,style='Card.TFrame')
    sidebar.pack(side='left',fill='y',padx=(0,22));sidebar.pack_propagate(False)
    def card_label(text,**kwargs):
        label=ttk.Label(sidebar,text=text,background=PANEL,**kwargs);label.pack(anchor='w');return label
    card_label('作業設定',font=('Microsoft JhengHei UI',13,'bold'))
    card_label('連續爬排位',foreground=GOLD).pack_configure(pady=(22,6))
    card_label('使用牌組',foreground=MUTED).pack_configure(pady=(14,8))
    app.deck_picker=ttk.Combobox(sidebar,state='readonly',width=22)
    app.deck_picker.pack(fill='x')
    app.deck_picker.bind('<<ComboboxSelected>>',app.select_deck)
    ttk.Button(sidebar,text='編輯牌組與打法',command=app.edit_deck).pack(fill='x',pady=(10,24))
    card_label('執行局數',foreground=MUTED)
    app.game_limit=tk.StringVar(value='0')
    ttk.Spinbox(sidebar,from_=0,to=999,textvariable=app.game_limit,width=9).pack(fill='x',pady=(8,6))
    card_label('指定局數後停止；0 表示持續執行。',foreground=MUTED,font=('Microsoft JhengHei UI',9))
    ttk.Separator(sidebar).pack(fill='x',pady=22)
    card_label('裝置連線',foreground=MUTED)
    app.connect_button=ttk.Button(sidebar,text='連線 MuMu',command=app.connect)
    app.connect_button.pack(fill='x',pady=(10,0))
    app.stop_button=ttk.Button(sidebar,text='停止作業 · F8',command=app.cancel,style='Stop.TButton')
    app.stop_button.pack(side='bottom',fill='x',pady=(10,0))
    app.start_button=ttk.Button(sidebar,text='開始作業',command=app.ranked,style='Accent.TButton')
    app.start_button.pack(side='bottom',fill='x',ipady=6)
    settings=ttk.Frame(body);settings.pack(side='left',fill='both',expand=True)
    status_box=ttk.Frame(settings,padding=18,style='Card.TFrame');status_box.pack(fill='x')
    app.activity_label=ttk.Label(status_box,text='●  待命',foreground=GOLD,background=PANEL,font=('Microsoft JhengHei UI',12,'bold'))
    app.activity_label.pack(anchor='w',pady=(0,10))
    status_label=ttk.Label(status_box,textvariable=app.status,wraplength=460,background=PANEL)
    status_label.pack(fill='x')
    status_box.bind('<Configure>',lambda e:status_label.configure(wraplength=max(120,e.width-40)))
    summary_label=ttk.Label(settings,textvariable=app.summary,style='Muted.TLabel',wraplength=460)
    summary_label.pack(fill='x',pady=(12,22))
    ttk.Label(settings,text='執行紀錄',style='Heading.TLabel').pack(anchor='w',pady=(0,10))
    log_box=ttk.Frame(settings);log_box.pack(fill='both',expand=True)
    app.run_log=tk.Text(log_box,height=10,wrap='word',state='disabled',bg='#1b1e22',fg=MUTED,
                        relief='flat',padx=14,pady=12,font=('Microsoft JhengHei UI',10),spacing3=6)
    log_scroll=ttk.Scrollbar(log_box,command=app.run_log.yview);log_scroll.pack(side='right',fill='y')
    app.run_log.configure(yscrollcommand=log_scroll.set);app.run_log.pack(fill='both',expand=True)
    ttk.Label(settings,text='每日、每週與活動任務將於後續版本加入。',style='Muted.TLabel',font=('Microsoft JhengHei UI',9)).pack(anchor='w',pady=(14,0))
    def refresh_controls():
        app.start_button.configure(state='disabled' if app.busy else 'normal')
        app.connect_button.configure(state='disabled' if app.busy else 'normal')
        app.stop_button.configure(state='normal' if app.busy else 'disabled')
        app.deck_picker.configure(state='disabled' if app.busy else 'readonly')
        app.activity_label.configure(text='●  執行中' if app.busy else ('●  已連線' if app.hands else '●  待命'))
    app.refresh_controls=refresh_controls
    refresh_controls()
    ttk.Button(preview,text='更新預覽',command=app.refresh).pack(side='bottom',anchor='e',pady=(10,0))
    observed=ttk.Frame(preview,width=310)
    observed.pack(side='right',fill='y',padx=(16,0))
    ttk.Label(observed,text='目前辨識資料').pack(anchor='w',pady=(0,10))
    app.observation_text=tk.Text(observed,width=34,wrap='word',state='disabled',bg=BG,fg=TEXT,
                                 relief='flat',font=('Microsoft JhengHei UI',10))
    scroll=ttk.Scrollbar(observed,command=app.observation_text.yview)
    scroll.pack(side='right',fill='y')
    app.observation_text.configure(yscrollcommand=scroll.set)
    app.observation_text.pack(fill='both',expand=True)
    app.canvas=tk.Canvas(preview,width=560,height=420,bg=BG,highlightthickness=1,highlightbackground='#404040')
    app.canvas.pack(fill='both',expand=True)
    app.canvas.bind('<Configure>',app.render_preview)
    def empty_preview(event):
        if not hasattr(app,'preview_image'):
            app.canvas.delete('all')
            app.canvas.create_text(event.width/2,event.height/2-16,text='尚未取得遊戲畫面',fill=TEXT,font=('Microsoft JhengHei UI',16,'bold'))
            app.canvas.create_text(event.width/2,event.height/2+22,text='連線 MuMu 後，按「更新預覽」。',fill=MUTED,font=('Microsoft JhengHei UI',10))
    app.canvas.bind('<Configure>',empty_preview,add='+')
    ttk.Label(library,text='牌組與打法',style='Heading.TLabel').pack(anchor='w')
    ttk.Label(library,text='每副牌組保存自己的模式、起手換牌、資源安排與 combo。',style='Muted.TLabel').pack(anchor='w',pady=(8,20))
    row=ttk.Frame(library);row.pack(anchor='w')
    ttk.Button(row,text='新增牌組',style='Accent.TButton',command=lambda:app.edit_deck(True)).pack(side='left',padx=(0,10))
    ttk.Button(row,text='編輯目前牌組',command=app.edit_deck).pack(side='left')
    ttk.Separator(library).pack(fill='x',pady=30)
    ttk.Label(library,text='HSReplay 環境資料',style='Heading.TLabel').pack(anchor='w')
    ttk.Label(library,text='從單一牌組的留牌指南匯入公開統計，保存來源、分段與時間範圍。\n相關手牌的數據會提供給 Laya；環境與 combo 心得可在「編輯目前牌組」保存。',style='Muted.TLabel',wraplength=850).pack(anchor='w',pady=12)
    refrow=ttk.Frame(library);refrow.pack(anchor='w',pady=(0,10))
    ttk.Button(refrow,text='匯入留牌參考',command=app.import_reference).pack(side='left',padx=(0,10))
    ttk.Button(refrow,text='查看已保存資料',command=app.show_reference).pack(side='left')
    ttk.Button(refrow,text='匯入環境榜',command=lambda:app.import_reference(True)).pack(side='left',padx=(10,0))
    ttk.Button(refrow,text='環境榜快照',command=app.show_meta).pack(side='left',padx=(10,0))
    ttk.Button(library,text='開啟 HSReplay 環境榜 ↗',command=lambda:webbrowser.open('https://hsreplay.net/zh-hant/meta/')).pack(anchor='w')
    def open_source():
        profile=app.profiles.selected() or {}
        if profile.get('source_url'):
            webbrowser.open(profile['source_url'])
        else:
            app.edit_deck()
    ttk.Button(library,text='開啟目前牌組來源 ↗',command=open_source).pack(anchor='w',pady=(8,0))
    ttk.Separator(library).pack(fill='x',pady=30)
    ttk.Label(library,text='後續版本',style='Heading.TLabel').pack(anchor='w')
    ttk.Label(library,text='每日任務  /  每週任務  /  活動任務\n目前先完成排位作業；任務自動化尚未開放。',style='Muted.TLabel').pack(anchor='w',pady=12)
    ttk.Label(advanced,text='裝置連線',style='Heading.TLabel').pack(anchor='w',pady=(0,10))
    ttk.Label(advanced,text='ADB 路徑',style='Muted.TLabel').pack(anchor='w')
    ttk.Entry(advanced,textvariable=app.adb,width=85).pack(fill='x',pady=(4,12))
    ttk.Label(advanced,text='MuMu 裝置位址',style='Muted.TLabel').pack(anchor='w')
    ttk.Entry(advanced,textvariable=app.serial,width=30).pack(anchor='w',pady=(4,22))
    ttk.Label(advanced,text='操作間隔 2.5 秒 · 未確認且局面未變時最多重試一次\n換牌及多步選取不自動重送，避免取消原選取。',style='Muted.TLabel').pack(anchor='w',pady=(0,16))
    row=ttk.Frame(advanced);row.pack(fill='x',pady=(0,18))
    for text,command in [('連續接手本局',app.continuous),('Laya 做一步',app.decide),('校準畫面',app.calibrate),('執行所選動作',app.execute_selected)]:
        ttk.Button(row,text=text,command=command).pack(side='left',padx=(0,8))
    app.table=ttk.Treeview(advanced,columns=('description',),show='headings',height=10)
    app.table.heading('description',text='目前合法動作');app.table.pack(fill='both',expand=True)
    app.update_deck_picker()
